site_name: kloppy 1.0.0
site_url: https://kloppy.pysport.org
repo_url: https://github.com/PySport/kloppy
repo_name: 'GitHub'
edit_uri: blob/master/docs/

# TODO: set-up Google Analytics project to track
google_analytics: null 

theme:
  name: material
  custom_dir: docs/overrides

nav:
  - Home: index.md
  - Quickstart Guides:
    - Event Data: quickstart/event_data.ipynb
    - Tracking Data: quickstart/tracking_data.ipynb
    - Examples: quickstart/examples.ipynb
  - Issues: 'issues.md'
  - Contributing: 'contributing.md'
  - Sponsors: 'sponsors.md'
  - About: 'about.md'
  - Changelog: 'changelog.md'
  - License: 'license.md'

plugins:
  - mkdocs-jupyter:
      include_source: True
  - search

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      linenums_style: table
